### ISSUE TITLE
What about freeradius 4?

### ISSUE THREAD

**Issue by pperzyna** [neutronth/rlm_raw#1]
as in topic

**Comment by neutronth** [comment]
I have a plan to work with FreeRADIUS 4 but I must focus at the stable release 3.0.x first.
Please stay tuned.

**Comment by jar3b** [comment]
This module is very useful for me, I builded docker container with freeradius 3.0.13 (alpine) supports rlm_raw out the box - it works fine!
If freeradius 3.1-4 has big advantages, I can support this module with PRs in future.
Now, for me 3.0 is enough.

**Comment by parmenides** [comment]
@jar3b Can you share your Dockerfile? I could not install raw module.

**Comment by alandekok** [comment]
This module will not be necessary in version 4.  The v4.0.x branch *today* supports dynamic clients, with all attributes decoded, and available to the unlang policies.

https://github.com/FreeRADIUS/freeradius-server/blob/v4.0.x/raddb/sites-available/dynamic-clients

**Comment by neutronth** [comment]
Thanks @alandekok , greatly appreciate your works.
